import fitdecode

'''
  Given a fit file, as generated by a Garmin ForeRunner 255,
  return the name of each public field.
'''
def get_fit_metadata(filePath: str) -> set:
  fields_seen = set()
 
  with fitdecode.FitReader(filePath) as fit:
      for frame in fit:
          if isinstance(frame, fitdecode.FitDataMessage) and frame.name == "record":
              for f in frame.fields:
                  fields_seen.add(f.name)
  return fields_seen

INPUT_FILE = "run_5kEmm_260616.fit"
f = get_fit_metadata(INPUT_FILE)
print(sorted(f))